recast-0-12:
  name: react-docgen
  versions: '>= 2.17.0 < 3.0.0 || >= 3.0.0-beta7 <= 3.0.0-beta10'
  peerDependencies: recast@0.12.6
  commands: npm run test:unit

recast-0-13:
  name: react-docgen
  versions: '>= 3.0.0-beta10 <= 3.0.0-beta12'
  peerDependencies: recast@0.13.0
  commands: npm run test:unit
